spring:
  application:
    name=f-ai-agent
  ai:
    dashscope:
      api-key: sk-0505b5ab01bb47eeb7d274120540f744
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v2
server:
  port:
    8123
  servlet:
    context-path: /api
# springdoc-openapi??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.feng.faiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
